.TH zux 1 "2026-08-25" "zux" "User Commands"
.SH NAME
zux \- mDNS-SD visualizer with force-directed graph
.SH SYNOPSIS
.B zux
.RI [ OPTIONS ]
.SH DESCRIPTION
zux is an mDNS-SD visualizer. It automatically discovers all services advertised
on your local network via multicast DNS service discovery (mDNS-SD), then renders
them as an interactive force-directed graph so you can see at a glance which
services, instances, hosts and addresses are present and how they relate to one
another.
.SH OPTIONS
.TP
.BI \-h , \-\-help
Print help
.TP
.BI \-V , \-\-version
Print version
.SH REPORTING ISSUES
Report bugs or issues at https://github.com/hrzlgnm/zux/issues
